KirbyDownB/Roomster

frontend/config-overrides.js, frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/components/Landing/Landing.css, frontend/src/components/Landing/Landing.js, frontend/src/components/Login/Login.css, frontend/src/components/Login/Login.js, frontend/src/index.css
This PR focuses on getting the login interface up. A screenshot is shown below
=> Login skeleton

frontend/src/assets/tail-spin.svg, frontend/src/components/Login/Login.css, frontend/src/components/Login/Login.js
From a user perspective, it would be nice to see different "login feedbacks", specifically when the user doesn't enter a username or password. In addition, the user can tell whether or not the login is still loading via a loading spinner. Below are screenshots demonstrating these different possible scenarios.
1. The user doesn't enter a username.
2. The user doesn't enter a password.
3. The user clicks the "login" button, causing the loading spinner to display.
=> Add user feedback for login

frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/src/App.js, frontend/src/assets/imgs/circle-logo.svg, frontend/src/components/Signup/Signup.css, frontend/src/components/Signup/Signup.js
- Added basic signup component 
- Added route 
- Still need to set up requests to backend for form
=> Js signup comp

frontend/src/index.js, frontend/src/redux/reducer/authentication.js
-Added redux directory with action.js file which will be updated in future PR
-Added reducer for authentication that sets user information in store
=> Task 7 (JS): setup redux store and authentication skeleton 

backend/apis/login.py, backend/apis/models.py, backend/apis/signup.py
This PR enables JWT functionality. 
When a user inputs their credentials, the identifier is checked to determine whether the user inputted a username or an email. Then, the user is retrieved from the database. If the password the user inputted is correct, the token is generated using the user's username and email address, and then returned to the front end.
A similar process occurs with signup. Once a user signs up, a token is returned containing the username and the email
=> Task 6: Return JWT when user is authenticated 

frontend/package-lock.json, frontend/package.json, frontend/src/components/Login/Login.js, frontend/src/const.js, frontend/src/index.js, frontend/src/redux/action.js, frontend/src/redux/reducer/authentication.js
=> Task 8: redux action and dispatch added for authenticating users on login

frontend/src/App.js, frontend/src/redux/action.js
-when a user refreshes, the token will be checked through a GET request 
-if token is invalid, the token is removed and user is essentially logged out
-if token is valid, the token should have a new time associated with it
-the dispatch is called in app.js to make sure that on refresh the user still has access to the protected routes
=> Task 10: added dispatch for refreshing token and included function call in app.js

frontend/src/App.js, frontend/src/components/PasswordReset/Reset.js
route will only render when a token is passed back and will only pertain to the user the token is issued to
=> Task 21: added route for when token is passed back by backend

backend/apis/__init__.py, backend/apis/login.py, backend/apis/passwordreset.py
This PR simply creates the endpoint for password reset
Inside the endpoint is some placeholder code. I will implement the functionality in future PR's
=> Task 19: Create Reset Password endpoint

frontend/src/components/Login/Login.css, frontend/src/components/Login/Login.js
In order to reset the user's password, the user must input his/her email address in the password reset input field. Clicking submit will send a request to the backend to reset the password associated to the email.
=> Task 16: Use popover for password reset

frontend/src/App.js, frontend/src/components/PasswordReset/ForgotPassword.css, frontend/src/components/PasswordReset/ForgotPassword.js
-forgot password component made 
-rendered after user clicks on url from email
=> Task 14: added forgotpassword component and route

backend/apis/__init__.py, backend/apis/login.py, backend/apis/models.py, backend/apis/passwordreset.py, backend/apis/signup.py
This PR does a few things.
1. Updates the user model using the edits we discussed yesterday
2. The user is emailed when they sign up or ask to reset their password
3. Allows the front end to send a password reset email using the endpoint 
`reset/email`
and then actually reset the password at
`reset/password`
=> Task 13: Set up Sendgrid api with link to password reset component

frontend/src/App.js, frontend/src/components/Login/Login.js, frontend/src/components/PasswordReset/ForgotPassword.js
password reset sent from email feature works properly now
=> Js routing password reset

frontend/src/components/Home/Profile/Profile.js
When the user edits information on his/her profile, the changes are reflected.
=> Task 26: Send and receive request for editing profile

frontend/src/components/Signup/Signup.css, frontend/src/components/Signup/Signup.js, frontend/src/constants.js, frontend/src/redux/action.js
The user can now upload a profile image on the frontend when signing up. In addition to that, the `ethnicity` input has been changed to a `Select` and a new input called `duration` has been added
=> Upload profile image in the frontend

frontend/src/App.js, frontend/src/components/Home/Feed/Feed.css, frontend/src/components/Home/Feed/Feed.js, frontend/src/components/Home/Home.js, frontend/src/constants.js
After the user logs in, the user can create a new post by clicking the "New Post" button.
=> New Post Form

frontend/package-lock.json, frontend/package.json, frontend/src/components/Home/Feed/Feed.css, frontend/src/components/Home/Feed/Feed.js, frontend/src/components/Home/Feed/Post/Post.css, frontend/src/components/Home/Feed/Post/Post.js, frontend/src/components/Home/Friends/Friends.js, frontend/src/components/Home/Profile/Profile.js, frontend/src/components/Home/Sidebar/Sidebar.css, frontend/src/components/Signup/Signup.js, frontend/src/constants.js, frontend/src/mocks.js
The user should be able to search for posts in his/her feed. When the user enters a query, the frontend feed cards will update with respect to what the user searches for (handled by the backend).
=> Query and receive search responses in the frontend

frontend/package-lock.json, frontend/package.json, frontend/src/components/Home/Feed/Feed.js, frontend/src/components/Home/Feed/Filter/Filter.css, frontend/src/components/Home/Feed/Filter/Filter.js, frontend/src/components/Home/Feed/Post/Post.css, frontend/src/constants.js, frontend/src/mocks.js
The user should be able to filter the feed using the `Filter` component located inside the `Popover`.
=> Set up filter select inputs

frontend/src/components/Home/Feed/Post/BasicProfile/BasicProfile.css, frontend/src/components/Home/Feed/Post/BasicProfile/BasicProfile.js, frontend/src/components/Home/Feed/Post/Post.css, frontend/src/components/Home/Feed/Post/Post.js, frontend/src/constants.js
When the user clicks on a name inside a`Post` in the `Feed`, a `Popover` will appear, where the user can add the other user as a friend.
=> Show popover to add friend from feed post

backend/apis/filter.py, backend/apis/friends.py, backend/apis/login.py, backend/apis/posting.py, backend/apis/retrieve_profile.py, backend/apis/search.py, backend/apis/signup.py, backend/apis/update_profile.py
Updates
1. Filter now has the ability to take priceMin and priceMax as parameters. It can also search with these using the MongoEngine abastraction
2. All non-successful returns now have an accompanying '400' error code
=> filter works

frontend/src/components/Home/Feed/Filter/Filter.js, frontend/src/components/Home/Profile/Profile.css, frontend/src/components/Home/Profile/Profile.js, frontend/src/components/Home/Sidebar/Sidebar.js, frontend/src/constants.js, frontend/src/redux/action.js
Some final touches
* Edit profile works properly
* Filter works properly
=> Final touches and fixes

backend/apis/__init__.py, backend/apis/listings.py, backend/apis/models.py, backend/apis/reviews.py, backend/requirements.txt
I added the review functionality. You can now submit and view reviews
=> Task 10: Create group schema, review schema and implement

frontend/src/components/Home/Feed/Feed.js, frontend/src/components/Home/Friends/Cards.css, frontend/src/components/Home/Friends/Cards.js, frontend/src/components/Home/Friends/Friends.css, frontend/src/components/Home/Friends/Friends.js, frontend/src/components/Home/Friends/ProfileModal/ProfileModal.css, frontend/src/components/Home/Friends/ProfileModal/ProfileModal.js, frontend/src/components/Home/Reviews/Reviews.css, frontend/src/components/Home/Reviews/Reviews.js, frontend/src/components/Home/Reviews/ReviewsCard/ReviewsCard.css, frontend/src/components/Home/Reviews/ReviewsCard/ReviewsCard.js, frontend/src/constants.js, frontend/src/mocks.js
This PR takes care of a couple things:
* The user can view reviews about their friends when they open their friend's profile modal
* The user can view all the reviews they've written in the new "Reviews" page, as well as reviews other people have written about them
* The user can sort reviews based on different criterions (Most Recent, Longest, Highest Rated, etc)
=> Task 2, Task 3: Render reviews on friend's profiles and allow users to sort reviews in the reviews page

backend/apis/__init__.py, backend/apis/groups.py, backend/apis/models.py, backend/app.py
Added an endpoint that turns a token into the users group object
=> More group stuff

backend/apis/groups.py
fixed functionality that previously required members field to be present on post request
=> Group fixes

frontend/config-overrides.js, frontend/package-lock.json, frontend/package.json, frontend/src/components/Home/Feed/Feed.css, frontend/src/components/Home/Feed/Feed.js, frontend/src/components/Home/Feed/Post/Post.css, frontend/src/components/Home/Feed/Search/Search.css, frontend/src/components/Home/Friends/Cards.css, frontend/src/components/Home/Friends/Friends.css, frontend/src/components/Home/Friends/Friends.js, frontend/src/components/Home/Friends/ProfileModal/ProfileModal.css, frontend/src/components/Home/Friends/ProfileModal/ProfileModal.js, frontend/src/components/Home/Home.js, frontend/src/components/Home/Notifications/Notifications.css, frontend/src/components/Home/Notifications/Notifications.js, frontend/src/components/Home/Profile/Profile.js, frontend/src/components/Home/Reviews/Reviews.js, frontend/src/components/Home/Reviews/ReviewsCard/ReviewsCard.css, frontend/src/components/Home/Sidebar/Sidebar.css, frontend/src/components/Home/Sidebar/Sidebar.js, frontend/src/constants.js, frontend/src/mocks.js, frontend/src/socket.js
* The user should be able to receive notifications in real-time, through the use of `socket.io`.
* The menu bar has a new tab called `Notifications`, which also displays the number of notifications. When the user clicks on the new tab, the active interface will show a list of all the notifications.
* The user can click on the "x" in each notification card to delete each notification individually.
* The user can click on the "Clear All" button to delete all the notifications at once
* The most recent notification will show up at the very top of the notifications list
=> Task 11, Task 13, Task 14: Set up web sockets, create notifications page, handle delete notifications

backend/apis/groups.py
Updates to group functionality:
1. groups now return all of the user object
2. Groups are now capped at 5 members
3. You can now remove posts. The endpoint is 
`/api/groups/delete_post/` , It's a DELETE request
=> Group functionality updates

backend/apis/dislike.py, backend/apis/friends.py, backend/apis/groups.py, backend/apis/like.py, backend/apis/notifications.py, backend/apis/reviews.py
Couple things
1. Delete notifications and delete all notifications works. The endpoints are
`api/notifications/delete/` and `api/notifications/delete_all/`
2. Leave group has been modified. If you leave a group with 2 people, the other person is removed and the group is deleted.
=> some more fixes

backend/apis/dislike.py, backend/apis/friends.py, backend/apis/like.py, backend/apis/reviews.py
=> Only call .to_json() and json.loads() just once
